name: STE
channels:
  - intel
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - h5py=2.10.0=py38h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - intel-openmp=2020.1=intel_217
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2020.1=intel_217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.0.15=py38ha843d7b_0
  - mkl_random=1.1.0=py38h962f231_0
  - more-itertools=8.2.0=py_0
  - mpi=1.0=mpich
  - mpi4py=3.0.3=py38h028fd6f_0
  - mpich=3.3.2=hc856adb_0
  - ncurses=6.2=he6710b0_0
  - numpy=1.18.1=py38h4f9e942_0
  - numpy-base=1.18.1=py38hde5b4d6_1
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.3=py_0
  - pip=20.0.2=py38_1
  - pluggy=0.13.1=py38_0
  - py=1.8.1=py_0
  - pyparsing=2.4.7=py_0
  - pytest=5.4.2=py38_0
  - pytest-timeout=1.3.4=py_0
  - python=3.8.1=h0371630_1
  - readline=7.0=h7b6447c_5
  - scipy=1.4.1=py38h0b6359f_0
  - setuptools=46.1.3=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h62c20be_1
  - tbb=2020.2=intel_217
  - tk=8.6.8=hbc83047_0
  - wcwidth=0.1.9=py_0
  - wheel=0.34.2=py38_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
prefix: /astro/mcnally/.conda/envs/STE

